name: Ujjwalt
favicon: null
layout_spectrum: 0.9492783753667027
typography_spectrum: 0.11077195079997182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.24703135038726032
  lightness: 0.9102461070287973
  saturation: 0.7481520962901413
  rhythmicContrast: 0.9872846002690494
purpose: []
